/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Hamburger(props) {
  const { nodes, materials } = useGLTF("./burger-draco.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="bottombun"
        castShadow
        receiveShadow
        geometry={nodes.bottombun.geometry}
        material={materials.bun}
        position={[-0.01, 0.17, 0]}
        scale={5.25}
      />
      <mesh
        name="topbun"
        castShadow
        receiveShadow
        geometry={nodes.topbun.geometry}
        material={materials.bun}
        position={[-0.01, 3.76, 0]}
        rotation={[0, 0, 3.14]}
        scale={5.25}
      />
      <mesh
        name="meat"
        castShadow
        receiveShadow
        geometry={nodes.meat.geometry}
        material={materials.meat}
        position={[-0.01, 0.97, 0]}
        scale={5.25}
      />
      <mesh
        name="cheese"
        castShadow
        receiveShadow
        geometry={nodes.cheese.geometry}
        material={materials.cheese}
        position={[0, -0.17, 0]}
      />
    </group>
  );
}

useGLTF.preload("./burger-draco.glb");
